CREATE TABLE IF NOT EXISTS user_otp (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_uuid CHAR(36) NOT NULL,
    otp_code_hash VARCHAR(100) NOT NULL,
    otp_type VARCHAR(50) NOT NULL,
    used_at DATETIME DEFAULT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    expired_at DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_by CHAR(36) DEFAULT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by CHAR(36) DEFAULT NULL,
    version INT DEFAULT 0
);